import type { MeHubSection, NavLabTab, PlaceLibraryFilter, PlaceLibraryGroup, PlaceLibraryItem, PlanPreview, TradeFilter, TradePreview } from "./navLab.types";

export const navLabTabs: NavLabTab[] = [
  {
    id: "plans",
    label: "Plans",
    tagline: "Open local or online plans with people.",
  },
  {
    id: "me",
    label: "Me",
    tagline: "Your activity, tools, and account in one calm hub.",
  },
  {
    id: "trade",
    label: "Trade",
    tagline: "Find one exchange at a time.",
  },
];

export const meHubSections: MeHubSection[] = [
  {
    id: "activity",
    title: "Activity",
    eyebrow: "What you are doing",
    summary: "Trades, proposals, needs, and offers stay together here instead of becoming separate main tabs.",
    items: [
      { id: "my-trades", label: "My trades", count: 4, subtitle: "Open and accepted exchanges" },
      { id: "proposals", label: "Proposals", count: 2, subtitle: "Private requests and replies" },
      { id: "my-needs", label: "My needs", count: 7, subtitle: "Things you are looking for" },
      { id: "my-offers", label: "My offers", count: 5, subtitle: "Skills, time, access, or objects" },
    ],
  },
  {
    id: "plans",
    title: "Plans",
    eyebrow: "Bigger goals",
    summary: "Created and joined plans stay separate from trades: local places, online sessions, and open social activities.",
    items: [
      { id: "created-plans", label: "Created plans", count: 3, subtitle: "Your open activities and drafts" },
      { id: "joined-plans", label: "Joined plans", count: 1, subtitle: "Plans you joined freely" },
      { id: "my-places", label: "My places", count: 3, subtitle: "Reusable offline and online places" },
    ],
  },
  {
    id: "tools",
    title: "Tools",
    eyebrow: "Personal utilities",
    summary: "Private organization tools stay close to the user without feeling like old account settings.",
    items: [
      { id: "saved-library", label: "Saved Library", count: 12, subtitle: "Saved people, trades, needs, and offers" },
      { id: "agenda", label: "Agenda", subtitle: "Private follow-ups and reminders" },
      { id: "notifications", label: "Notifications", count: 3, subtitle: "Updates that need attention" },
    ],
  },
  {
    id: "account",
    title: "Account",
    eyebrow: "Profile and settings",
    summary: "The account area becomes a smaller section instead of the whole identity of the tab.",
    items: [
      { id: "public-profile", label: "Public profile", subtitle: "How others see you" },
      { id: "settings", label: "Settings", subtitle: "Language, privacy, and preferences" },
      { id: "support", label: "Support", subtitle: "Help, safety, and feedback" },
    ],
  },
];

export const placeLibraryFilters: PlaceLibraryFilter[] = [
  {
    id: "all",
    label: "All places",
    helper: "Offline and online places together.",
  },
  {
    id: "offline",
    label: "Offline",
    helper: "Local addresses, public places, routes, cafes, parks, and meeting points.",
  },
  {
    id: "online",
    label: "Online",
    helper: "Platforms, calls, community rooms, files, and online session spaces.",
  },
];

export const placeLibraryGroups: PlaceLibraryGroup[] = [
  {
    id: "my_place",
    label: "My places",
    helper: "Reusable offline and online places created by the user.",
  },
  {
    id: "starter_place",
    label: "Starter places",
    helper: "Template places users can copy into their own plans before creating official places.",
  },
];

export const myPlaceLibrary: PlaceLibraryItem[] = [
  {
    id: "my-republique-cafe",
    source: "my_place",
    kind: "local_place",
    title: "Cafe near Republique",
    category: "offline-cafe",
    categoryLabel: "Offline · Cafe",
    addressOrPlatform: "Paris 11e",
    areaLabel: "Republique",
    description: "A casual cafe meeting point for small open plans, first hellos, and calm table conversations.",
    imageLabels: ["Cafe front", "Small table", "Street corner"],
    ownerName: "Kopy",
    visibility: "public",
    accessLabel: "Public place",
    defaultTimeLabel: "15:00",
    defaultNote: "Meet, say hello, and choose a small table.",
    useLabel: "Use this place",
  },
  {
    id: "my-canal-walk",
    source: "my_place",
    kind: "local_place",
    title: "Canal Saint-Martin walk",
    category: "offline-walk",
    categoryLabel: "Offline · Walk",
    addressOrPlatform: "Paris 10e",
    areaLabel: "Canal Saint-Martin",
    description: "A simple public walking route for language practice, photos, and low-pressure social plans.",
    imageLabels: ["Canal view", "Bridge", "Walking path"],
    ownerName: "Kopy",
    visibility: "public",
    accessLabel: "Public route",
    defaultTimeLabel: "16:00",
    defaultNote: "Walk, take photos, and continue the conversation.",
    useLabel: "Add to plan",
  },
  {
    id: "my-discord-lobby",
    source: "my_place",
    kind: "online_place",
    title: "Discord lobby",
    category: "online-community",
    categoryLabel: "Online · Community",
    addressOrPlatform: "Discord",
    areaLabel: "Online",
    description: "A reusable online lobby for intros, quick coordination, and sharing links before a remote plan starts.",
    imageLabels: ["Discord visual", "Voice room", "Welcome channel"],
    ownerName: "Kopy",
    visibility: "private",
    accessLabel: "Access note hidden",
    defaultTimeLabel: "20:30",
    defaultNote: "Quick intro and link sharing before the review.",
    useLabel: "Use online place",
  },
];

export const starterPlaceLibrary: PlaceLibraryItem[] = [
  {
    id: "starter-study-cafe",
    source: "starter_place",
    kind: "local_place",
    title: "Study cafe table",
    category: "offline-cafe",
    categoryLabel: "Offline · Starter cafe",
    addressOrPlatform: "Choose a cafe area",
    areaLabel: "Local starter",
    description: "A starter offline place for people who want to open a calm study, feedback, or coworking plan.",
    imageLabels: ["Cafe table", "Notebook", "Quiet corner"],
    ownerName: "Hellowhen",
    visibility: "verified_later",
    accessLabel: "Starter template",
    defaultTimeLabel: "Afternoon",
    defaultNote: "Meet at a public cafe and keep the plan light.",
    useLabel: "Start from this",
  },
  {
    id: "starter-public-park",
    source: "starter_place",
    kind: "local_place",
    title: "Public park walk",
    category: "offline-walk",
    categoryLabel: "Offline · Starter walk",
    addressOrPlatform: "Choose a park",
    areaLabel: "Local starter",
    description: "A starter public place for walking, language practice, photos, or casual social plans.",
    imageLabels: ["Park path", "Open bench", "Green area"],
    ownerName: "Hellowhen",
    visibility: "verified_later",
    accessLabel: "Starter template",
    defaultTimeLabel: "Weekend",
    defaultNote: "Walk in a public place and keep the meeting simple.",
    useLabel: "Start from this",
  },
  {
    id: "starter-google-meet",
    source: "starter_place",
    kind: "online_place",
    title: "Google Meet session",
    category: "online-call",
    categoryLabel: "Online · Starter call",
    addressOrPlatform: "Google Meet",
    areaLabel: "Online starter",
    description: "A starter online place for remote introductions, feedback sessions, and small group calls.",
    imageLabels: ["Meet visual", "Call screen", "Online room"],
    ownerName: "Hellowhen",
    visibility: "verified_later",
    accessLabel: "Starter template",
    defaultTimeLabel: "Evening",
    defaultNote: "Open the call, welcome people, and keep the session focused.",
    useLabel: "Start from this",
  },
  {
    id: "starter-figma-review",
    source: "starter_place",
    kind: "online_place",
    title: "Figma review room",
    category: "online-creative",
    categoryLabel: "Online · Starter creative",
    addressOrPlatform: "Figma",
    areaLabel: "Online starter",
    description: "A starter online place for design review, product feedback, and visual brainstorming plans.",
    imageLabels: ["Figma board", "Comment pins", "Review notes"],
    ownerName: "Hellowhen",
    visibility: "verified_later",
    accessLabel: "Starter template",
    defaultTimeLabel: "Flexible",
    defaultNote: "Share the board and ask people to leave short visual comments.",
    useLabel: "Start from this",
  },
];

export const placeLibraryItems: PlaceLibraryItem[] = [...myPlaceLibrary, ...starterPlaceLibrary];

export const planPreviews: PlanPreview[] = [
  {
    id: "paris-creative-afternoon",
    category: "Local",
    title: "Paris creative afternoon",
    status: "open",
    mode: "local",
    summary: "Coffee, a short walk, and a calm work session arranged as an open plan people can freely join.",
    ownerName: "Mina",
    startLabel: "Sat 15:00",
    placeSummary: "Republique → Canal → Coworking cafe",
    joinedCount: 4,
    joinedPreview: ["Mina", "Leo", "Nora", "Yanis"],
    capacityLabel: "Open spots",
    joinLabel: "Join plan",
    places: [
      {
        id: "republique-cafe",
        libraryPlaceId: "my-republique-cafe",
        placeSource: "my_place",
        kind: "local_place",
        order: 1,
        title: "Cafe near Republique",
        addressOrPlatform: "Paris 11e",
        timeLabel: "15:00",
        note: "Meet, say hello, and choose a small table.",
        imageLabel: "Cafe image",
      },
      {
        id: "canal-walk",
        libraryPlaceId: "my-canal-walk",
        placeSource: "my_place",
        kind: "local_place",
        order: 2,
        title: "Canal Saint-Martin walk",
        addressOrPlatform: "Paris 10e",
        timeLabel: "16:00",
        note: "Walk, take photos, and continue the conversation.",
        imageLabel: "Canal image",
      },
      {
        id: "coworking-cafe",
        kind: "local_place",
        order: 3,
        title: "Small coworking cafe",
        addressOrPlatform: "Near Gare de l'Est",
        timeLabel: "17:00",
        note: "Quiet work block for anyone who wants to stay.",
        imageLabel: "Workspace image",
      },
    ],
  },
  {
    id: "online-design-review",
    category: "Online",
    title: "Online design review session",
    status: "open",
    mode: "online",
    summary: "A lightweight online plan with ordered platform stops for intro, review, and final notes.",
    ownerName: "Alex",
    startLabel: "Tonight 20:30",
    placeSummary: "Discord → Figma → Google Meet",
    joinedCount: 6,
    joinedPreview: ["Alex", "Maya", "Sam", "Ines", "+2"],
    capacityLabel: "Open online",
    joinLabel: "Join online",
    places: [
      {
        id: "discord-intro",
        libraryPlaceId: "my-discord-lobby",
        placeSource: "my_place",
        kind: "online_place",
        order: 1,
        title: "Discord lobby",
        addressOrPlatform: "Discord",
        timeLabel: "20:30",
        note: "Quick intro and link sharing before the review.",
        imageLabel: "Discord visual",
      },
      {
        id: "figma-review",
        libraryPlaceId: "starter-figma-review",
        placeSource: "starter_place",
        kind: "online_place",
        order: 2,
        title: "Figma board",
        addressOrPlatform: "Figma",
        timeLabel: "20:45",
        note: "Everyone leaves short visual comments.",
        imageLabel: "Figma visual",
      },
      {
        id: "meet-wrap",
        libraryPlaceId: "starter-google-meet",
        placeSource: "starter_place",
        kind: "online_place",
        order: 3,
        title: "Wrap-up call",
        addressOrPlatform: "Google Meet",
        timeLabel: "21:15",
        note: "Share the best feedback and next steps.",
        imageLabel: "Meet visual",
      },
    ],
  },
  {
    id: "sunday-language-walk",
    category: "Mixed",
    title: "Sunday language walk",
    status: "draft",
    mode: "mixed",
    summary: "A mixed plan that starts online for introductions, then continues with a local language walk.",
    ownerName: "Sara",
    startLabel: "Sun 11:00",
    placeSummary: "WhatsApp → Luxembourg Gardens",
    joinedCount: 0,
    joinedPreview: ["Sara"],
    capacityLabel: "Draft",
    joinLabel: "Preview plan",
    places: [
      {
        id: "whatsapp-intro",
        kind: "online_place",
        order: 1,
        title: "WhatsApp intro",
        addressOrPlatform: "WhatsApp",
        timeLabel: "10:30",
        note: "Confirm who is coming before meeting outside.",
        imageLabel: "Chat visual",
      },
      {
        id: "luxembourg-gardens",
        libraryPlaceId: "starter-public-park",
        placeSource: "starter_place",
        kind: "local_place",
        order: 2,
        title: "Luxembourg Gardens",
        addressOrPlatform: "Paris 6e",
        timeLabel: "11:00",
        note: "Walk and practice French / English in pairs.",
        imageLabel: "Garden image",
      },
    ],
  },
];

export const tradeFilters: TradeFilter[] = [
  {
    id: "all",
    label: "All",
    helper: "Trades, open needs, open offers, and starter ideas together.",
  },
  {
    id: "trades",
    label: "Trades",
    helper: "Need plus offer exchange cards only.",
  },
  {
    id: "needs",
    label: "Needs",
    helper: "Open needs from people who are still deciding what they can offer.",
  },
  {
    id: "offers",
    label: "Offers",
    helper: "Open offers from people ready to help first.",
  },
];

export const tradePreviews: TradePreview[] = [
  {
    id: "landing-photos",
    type: "trade",
    needTitle: "Landing page feedback",
    offerTitle: "Product photos",
    meta: "Remote · Creative · 7 days left",
    footerLabel: "Open trade",
  },
  {
    id: "french-walk-video",
    type: "trade",
    needTitle: "Practice French on a walk",
    offerTitle: "Basic video editing help",
    meta: "Paris · Social · This week",
    footerLabel: "Open trade",
  },
  {
    id: "open-need-admin-letter",
    type: "open_need",
    title: "Explain a French admin letter",
    meta: "Open need · Local / remote · Flexible",
    footerLabel: "Offer help",
  },
  {
    id: "open-offer-product-photos",
    type: "open_offer",
    title: "I can take simple product photos outdoors",
    meta: "Open offer · Creative · Weekend",
    footerLabel: "Use this offer",
  },
  {
    id: "starter-tripod-photos",
    type: "starter",
    needTitle: "Borrow a tripod for one day",
    offerTitle: "Edit five photos",
    meta: "Starter idea · Object / access",
    footerLabel: "Create your version",
    placementNote: "Preview: appears after a few real items when the feed is quiet.",
  },
  {
    id: "open-need-quiet-table",
    type: "open_need",
    title: "Find a quiet table for a video call",
    meta: "Open need · Access · Today",
    footerLabel: "Offer a place",
  },
];
