import type { ChainLabScenario } from "./chainLab.types";

export const chainLabScenario: ChainLabScenario = {
  id: "chain-lab-001",
  title: "Chain Match",
  subtitle: "3-person exchange",
  statusLabel: "Suggested",
  helperText: "Tap a person to see their role in the exchange.",
  currentUserId: "you",
  order: ["sara", "alex", "you"],
  participants: [
    {
      id: "you",
      name: "You",
      initials: "YO",
      roleLabel: "Your role",
      needTitle: "Landing page feedback",
      offerTitle: "Product photos",
      receivesFromId: "alex",
      givesToId: "sara",
      timingLabel: "This week",
      modeLabel: "Remote",
      effortLabel: "1-2h",
      joined: true,
    },
    {
      id: "sara",
      name: "Sara",
      initials: "SA",
      roleLabel: "Participant",
      needTitle: "Product photos",
      offerTitle: "French proofreading",
      receivesFromId: "you",
      givesToId: "alex",
      timingLabel: "Weekend",
      modeLabel: "Remote",
      effortLabel: "1h",
      joined: true,
    },
    {
      id: "alex",
      name: "Alex",
      initials: "AX",
      roleLabel: "Participant",
      needTitle: "French proofreading",
      offerTitle: "Landing page feedback",
      receivesFromId: "sara",
      givesToId: "you",
      timingLabel: "This week",
      modeLabel: "Remote",
      effortLabel: "30 min",
      joined: false,
    },
  ],
};
